# Generated by Django 4.1.2 on 2022-10-24 22:42

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("projects", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="modelo",
            new_name="Projects",
        ),
    ]
