# Generated by Django 4.1.2 on 2022-10-24 22:43

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("projects", "0002_rename_modelo_projects"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Projects",
            new_name="Project",
        ),
    ]
